### ISSUE TITLE
Update rubygems for v0.5.0

### ISSUE THREAD

**Issue by dmitry** [rgeo/activerecord-mysql2spatial-adapter#17]
Version 0.5.0 was released 17 days ago (as I write this text), but on the rubygems there are still the latest 0.4.3: https://rubygems.org/gems/activerecord-mysql2spatial-adapter

Is it accidentally isn't updated on rubygems or it's still not released?

**Comment by januszm** [comment]
Thanks for pointing that out. I wanted to spend a bit more time and test more thoroughly, that's why it hasn't been released to rubygems yet. I couldn't spend more time on this recently though.

I've just pushed it to rubygems as 0.5.0.nonrelease. I planned to do much more code cleanup some day and then release it as 0.5.1.

**Comment by dmitry** [comment]
@januszm thanks for working on this gem and pushing 0.5.0 to rubygems! :+1:
